-- MySQL Script generated by MySQL Workbench
-- 02/16/17 11:17:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema honbab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema honbab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `honbab` DEFAULT CHARACTER SET utf8 ;
USE `honbab` ;

-- -----------------------------------------------------
-- Table `honbab`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honbab`.`member` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'member ID 값',
  `userid` VARCHAR(45) NOT NULL COMMENT '회원 아이디',
  `password` VARCHAR(255) NOT NULL COMMENT '회원 비밀번호',
  `name` VARCHAR(11) NOT NULL COMMENT '회원이름',
  `nickname` VARCHAR(11) NOT NULL COMMENT '별명',
  `gender` VARCHAR(1) NOT NULL COMMENT '성별',
  `phone` VARCHAR(11) NULL DEFAULT NULL COMMENT '핸드폰번호',
  `regdate` VARCHAR(45) NULL DEFAULT NULL COMMENT '생성날짜',
  `editdate` VARCHAR(45) NULL DEFAULT NULL COMMENT '수정날짜',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `honbab`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honbab`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '게시글 ID',
  `member_id` INT NOT NULL COMMENT 'member table 고유 ID',
  `subject` VARCHAR(45) NOT NULL COMMENT '제목',
  `category` VARCHAR(1) NOT NULL COMMENT '레시피인지 요청글인지 분류',
  `text` VARCHAR(255) NULL COMMENT '요청시 작성 글',
  `title_image` VARCHAR(255) NULL COMMENT '썸네일 사진',
  `level` INT(1) NULL COMMENT '난이도',
  `time` INT(4) NULL COMMENT '소요시간(1~9999)분',
  `recipe_category` VARCHAR(11) NULL COMMENT '음식의 종류',
  `ingredient1` VARCHAR(255) NULL COMMENT '재료',
  `ingredient2` VARCHAR(255) NULL COMMENT '재료2( 글자 수 가 넘어갈 경우 보조역할)',
  `recipe_simple` VARCHAR(255) NULL COMMENT '음식의 간략 설명',
  `reg_date` VARCHAR(45) NULL COMMENT '생성날짜',
  `edit_date` VARCHAR(45) NULL COMMENT '수정 날짜',
  PRIMARY KEY (`id`),
  INDEX `member_idx` (`member_id` ASC),
  CONSTRAINT `member`
    FOREIGN KEY (`member_id`)
    REFERENCES `honbab`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `honbab`.`step`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honbab`.`step` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '고유 id값',
  `step_no` VARCHAR(45) NOT NULL COMMENT '순서',
  `article_id` INT NOT NULL COMMENT '글 ID',
  `text` VARCHAR(255) NULL COMMENT '설명',
  `image` VARCHAR(255) NULL COMMENT '이미지파일',
  `reg_date` VARCHAR(45) NULL COMMENT '작성 날짜',
  `edit_date` VARCHAR(45) NULL COMMENT '편집 날짜',
  PRIMARY KEY (`id`),
  INDEX `fk_step_article1_idx` (`article_id` ASC),
  CONSTRAINT `fk_step_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `honbab`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `honbab`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `honbab`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'id값',
  `member_id` INT NOT NULL COMMENT 'member table의 고유 ID값',
  `article_id` INT NOT NULL COMMENT '글 ID',
  `text` VARCHAR(255) NOT NULL COMMENT '내용',
  `reg_date` VARCHAR(45) NULL COMMENT '생성날짜',
  `edit_date` VARCHAR(45) NULL COMMENT '수정 날짜',
  PRIMARY KEY (`id`),
  INDEX `article_idx` (`article_id` ASC),
  INDEX `member_idx` (`member_id` ASC),
  CONSTRAINT `article`
    FOREIGN KEY (`article_id`)
    REFERENCES `honbab`.`article` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `member`
    FOREIGN KEY (`member_id`)
    REFERENCES `honbab`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
